### ISSUE TITLE
2.9.6 Issues

### ISSUE THREAD

**Issue by ghost** [SEModCommunity/SE-Community-Mod-API#109] opened 2014-08-15 23:42 UTC
My server just shuts down after about 10-20 mins. I reverted back to 2.9.5 and it seems to be fine. 

What are the logs you need and where are they located.  

Thanks,

-New

**Comment by ghost** [comment] 2014-08-15 23:55
http://pastebin.com/9skbwtCt

**Comment by ghost** [comment] 2014-08-16 00:07
I did a complete re-install, let's see if this work. I'll report back

**Comment by ghost** [comment] 2014-08-16 00:09
Shut off right away... What am I doing wrong?

http://pastebin.com/SzSebp8n

**Comment by ghost** [comment] 2014-08-16 00:53
Ran for a good amount of time then it shut off:

**Comment by ghost** [comment] 2014-08-16 00:53
Latest Crash:

http://pastebin.com/uXWSgJJ5

**Comment by ghost** [comment] 2014-08-16 01:06
Disabled all mods, will post if this fixes the issue.

**Comment by chessmaster42** [comment] 2014-08-16 01:28
This is a known game bug with floating objects as of 1.043 and not a bug with SEServerExtender or the SEModAPI. As such I am closing this issue.

**Closed as completed by chessmaster42** 2014-08-16 01:28 UTC
