### ISSUE TITLE
Minor Annoyance: When the server starts the scroll bar in server properties disappears

### ISSUE THREAD

**Issue by mikeloeven** [SEModCommunity/SE-Community-Mod-API#137] opened 2014-09-04 22:24 UTC
marking this as a low priority annoyance but when the server loads the scroll bar for the properties window disappears preventing the user from seeing all the selected options if they need to check something

**Comment by chessmaster42** [comment] 2014-09-05 00:02
Closing as duplicate of #62

**Closed as completed by chessmaster42** 2014-09-05 00:02 UTC
Labels: Duplicate
