### ISSUE TITLE
OnCubeBlockCreated spam

### ISSUE THREAD

**Issue by DraygoKorvan** [SEModCommunity/SE-Community-Mod-API#77] opened 2014-07-24 22:29 UTC
Currently the extender is spamming the OnCubeBlockCreated method in the plugin nonstop when no items are being created.

**Comment by chessmaster42** [comment] 2014-07-25 17:25
Issue confirmed. Partial fix is in the repo but this isn't completely fixed yet. Please retest latest source build and let me know how much better/worse it is now.

**Comment by DraygoKorvan** [comment] 2014-07-25 20:24
should be fixed, it is no longer spamming

**Comment by DraygoKorvan** [comment] 2014-07-25 20:47
yep, not yet fixed still getting this.

**Comment by DraygoKorvan** [comment] 2014-07-27 20:22
I think I got some insight as to why this is happening. My oncubeblockcreated function may be taking longer to execute before the next call of oncubeblock created, resulting in the oncubeblockcreated method being called again. Quick way to duplicate is to make a plugin with Thread.Sleep(1000) at the front of it. (though I'm not actually doing that in my method)

**Comment by chessmaster42** [comment] 2014-08-06 15:19
As there has been no further info on this for a week and since Draygo is overhauling the plugin manager anyway I am closing this issue out.

**Closed as completed by chessmaster42** 2014-08-06 15:19 UTC
Labels: Bug, On hold, Internal API
