### ISSUE TITLE
Request Feature: Change Server Settings - Add/Remove Mods

### ISSUE THREAD

**Issue by derrickmehaffy** [SEModCommunity/SE-Community-Mod-API#138] opened 2014-09-05 10:39 UTC
We have the ability to change all other important server settings via SEServerExtender however I do not see an option to add or remove mods that is provided in the dedicated server GUI.

**Comment by chessmaster42** [comment] 2014-09-05 15:14
Closed as duplicate of #116

**Closed as completed by chessmaster42** 2014-09-05 15:14 UTC
Labels: Duplicate
