### ISSUE TITLE
API Crash if Game Location can't be Automatically Retrieve

### ISSUE THREAD

**Issue by generalwrex** [SEModCommunity/SE-Community-Mod-API#33] opened 2014-06-18 17:34 UTC
Having an issue getting the release to run on 8.1, I'm not getting any errors, it just wont start.

 I tried to build the source in vs 2013 and this error came up;
"An unhandled exception of type 'SEModAPI.Support.AutoException' occurred in SEModAPI.dll"

just reporting whats happening :)

same issue on both versions

**Comment by fvgoulet** [comment] 2014-06-18 21:20
Its only an exception that is not handled. We will resolve this issue today.

**Comment by generalwrex** [comment] 2014-06-18 21:34
Alright :)

**Comment by fvgoulet** [comment] 2014-06-18 21:48
My guess is that your game is not installed or corrupted. It could be something else but an AutoException is thrown when the game installation is corrupted or missing in the registry. It work for me on Win 8.1. We will add the proper exception management though.

**Comment by generalwrex** [comment] 2014-06-18 21:54
it was installed via steam under the default path under "steamapps/common", i haven't checked the registry for entries regarding it, do you happen to know where they would be?

edit: the game works fine btw

**Comment by generalwrex** [comment] 2014-06-18 23:08
Maybe add in a path dialog if it cant find the game?

**Comment by generalwrex** [comment] 2014-06-19 03:59
It seemed that I copied over my space engineers folder from another HD, so it was never properly installed via steam. :)

**Comment by Moustachauve** [comment] 2014-06-19 04:21
Thank you, I will look over to make it possible to select the game location manually if it is not found.

**Comment by Moustachauve** [comment] 2014-06-19 07:58
This should be complete, waiting for code review

**Comment by fvgoulet** [comment] 2014-06-19 13:43
@generalwrex Can you reproduce this issue now? Let us know, we will enhance the solution if you are able to.

**Comment by generalwrex** [comment] 2014-06-19 17:01
Tried to rename the SpaceEngineers folder but no joy on a dialog popup.

edit:  The exception that i got before was caught by the program this time, allowing me to hit continue, program started up with no dialog..even though i renamed the folder. 

What about an options window with path and other settings? 

Also making the program ask for the location first run no matter if it can find the game or not.

**Comment by Moustachauve** [comment] 2014-06-19 18:23
This is exactly what have been done, it just was not released yet. Can you try it by compiling the source?

**Comment by chessmaster42** [comment] 2014-06-23 03:54
This update has now been released as v0.2.3-config-alpha. Please try the latest version and see if everything is working for you now.

**Comment by chessmaster42** [comment] 2014-06-25 07:04
Closing this out as there has been no response from reporter and the tool has changed several times over since this version.

**Closed as completed by chessmaster42** 2014-06-25 07:04 UTC
Labels: Bug, Completed
